// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelScheduleArrange.Api.Data;

#nullable disable

namespace TravelScheduleArrange.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905033432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TravelScheduleArrange.Api.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("TravelScheduleArrange.Api.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("TargetLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetLongitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("TravelScheduleArrange.Api.Models.ItineraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttractionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanceFromPrevious")
                        .HasColumnType("REAL");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("ItineraryId", "Order");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("TravelScheduleArrange.Api.Models.ItineraryItem", b =>
                {
                    b.HasOne("TravelScheduleArrange.Api.Models.Attraction", "Attraction")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelScheduleArrange.Api.Models.Itinerary", "Itinerary")
                        .WithMany("Items")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("TravelScheduleArrange.Api.Models.Attraction", b =>
                {
                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("TravelScheduleArrange.Api.Models.Itinerary", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
